name: Deployment (Production)
on:
  push:
    branches: ['master']

  repository_dispatch:
    types: [webhook]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn install
      - name: Generate
        env:
          CMS_API_KEY: ${{ secrets.CMS_API_KEY }}
          CMS_BASE_URL: ${{ secrets.CMS_BASE_URL }}
        run: yarn generate:production
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
